- name: create VPC
  ec2_vpc_net:
    state: present
    name: "{{ vpc.name }}"
    cidr_block: "{{ vpc.cidr }}"
    region: "{{ vpc.region }}"
    tags:
      Role: eks
  register: create_vpc

- name: "set fact: VPC ID"
  set_fact:
    vpc_id: "{{ create_vpc.vpc.id }}"

- name: create VPC subnets
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ item.value.cidr }}"
    az: "{{ item.value.az }}"
    tags:
      Name: "{{ item.key }}"
      Role: eks
  with_dict: "{{ subnets }}"
  register: create_vpc_subnets

- name: "set fact: VPC subnet 0 ID"
  set_fact:
    subnet0_id: "{{ create_vpc_subnets.results[0].subnet.id }}"

- name: "set fact: VPC subnet 1 ID"
  set_fact:
    subnet1_id: "{{ create_vpc_subnets.results[1].subnet.id  }}"

- name: "set fact: VPC subnet 2 ID"
  set_fact:
    subnet2_id: "{{ create_vpc_subnets.results[2].subnet.id  }}"


- ec2_vpc_igw:
    vpc_id: "{{ vpc_id }}"
    tags:
      Name: eks-igw
      Role: eks
    state: present
  register: igw

# Basic creation example:
- name: Set up public subnet route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_id }}"
    region: eu-west-1
    tags:
      Name: eks-rt
      Role: eks
    subnets:
      - "{{ subnet0_id }}"
      - "{{ subnet1_id }}"
      - "{{ subnet2_id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
  register: eks_route_table