ansible_connection: local

role:
  tag: eks

eks_cluster_name: my-eks-cluster

eks_cluster_role_name: "{{ role.tag }}-cluster-role"
eks_worker_role_name:  "{{ role.tag }}-worker-role"

eks_kubeconfig: ~/.kube/{{ eks_cluster_name }}.config

vpc:
  name: "{{ role.tag }}-vpc"
  region: eu-west-1
  cidr: 10.10.0.0/16

subnets:
  "{{ role.tag }}-{{ vpc.region }}a":
    cidr: 10.10.1.0/24
    az: "{{ vpc.region }}a"
  "{{ role.tag }}-{{ vpc.region }}b":
    cidr: 10.10.2.0/24
    az: "{{ vpc.region }}b"
  "{{ role.tag }}-{{ vpc.region }}c":
    cidr: 10.10.3.0/24
    az: "{{ vpc.region }}c"

security_groups:
  - name: vpc-all
    description: "Allow internal traffic in the VPC"
    rules:
      - proto: all
        group_name: vpc-all
        from_port: 0
        to_port: 65000


  - name: allow-public-ssh
    description: "Allow public SSH"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 22

  - name: allow-public-http
    description: "Allow public web traffic"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 80
          - 443